### PR TITLE
fix: set toast position based on safe area insets

### LINKED ISSUE #51: Notifications hide under screen notch
add proper inset/padding so that notifications don't hide under screen notch

### PR DESCRIPTION
**Pull request by wjkg**
Fixes #51 
- sets `topOffset` option for toasts based on safe area inset

image

### CODE REVIEW

File: components/drawer/CustomDrawerLayout.tsx [hunk 1]
```diff
@@ -54,8 +54,8 @@ const CustomDrawerLayout = ({ children }: { children: React.ReactNode }) => {
     });
   };
 
-  const toastConfig = {
-    defaultToast: ({ text1 }: any) => (
+  const toastConfig: ToastConfig = {
+    defaultToast: ({ text1 }) => (
```
Comment (mkopcins) [inline components/drawer/CustomDrawerLayout.tsx:58]:
```suggestion
    defaultToast: ({ text }) => (
```

**Review by mkopcins — CHANGES_REQUESTED** [review]
